### ISSUE TITLE
Create a folder called set 2 and a file in it containing the Repo heading/title and the description 

### ISSUE THREAD

**Issue by Dkingofcode** [Ifycode/git-github-training#13]
> Task: Create a folder called set 2 and a file in it. The name of the file should be README.md. This readme file should contain the Repo heading/title and the description.

> Task: Create a folder called set 2 and a file in it. The name of the file should be README.md. This readme file should contain the Repo heading/title and the description.

**Comment by Ifycode** [comment]
@Dkingofcode Link this issue to the PR you submitted.
